### PR TITLE
Fix memory leak

### LINKED ISSUE #366: Memory leak
Frankenphp seems to be leaking memory (at least in my specific configuration). I first noticed it when benchmarking it. It would staircase to heaven with each request passing through it, eventually getting killed by OOM killer. Just now I noticed that its memory usage keeps growing while idle as well (well, almost idle; it still handles healthchecks). Below you'll find a screenshot showing an idle frankenphp pod growing both in memory usage and CPU usage while receiving 1 request every 5 seconds from an ELB. Whatever is leaking is also adding on the CPU workload.

Screenshot:
https://imgur.com/a/a6wbI2A

Setup:
- custom docker image built from the official one
- arm64
- worker mode (I *think* only worker mode exhibits this behavior, but I haven't really checked)
- `FrankenPHP v1.0.0 PHP 8.3.0 Caddy v2.7.5 h1:HoysvZkLcN2xJExEepaFHK92Qgs7xAiCFydN5x5Hs6Q=`
- Symfony app (api platform) w/ frankenphp-runtime (a fork, actually)

```
[PHP Modules]
amqp
apcu
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
intl
json
ldap
libxml
mbstring
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
random
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

Let me know how can I help to get to the bottom of this. I'm not really familiar with the development tools involved in golang/caddy/frankenphp, but I'm a quick learner.

### PR DESCRIPTION
**Pull request by withinboredom**
It appears we aren't deleting ALL the created handles. This PR introduces a "smartpointer.go" file which can manage handles (and pointers, though it isn't used in this PR -- can remove the pointer code) without having to keep track of them manually. I like it because it frees up the cognitive load when trying to ensure everything is actually freed, without having to trace through the entire program's execution to figure out whether or not it is freed. 

To illustrate the difference, here are screen shots after 1:15 of running a load-test on a 2gb container (pay attention to memory usage).

fixes #366 

image

^ before this change

image

^ after this change (~7k RPS!)

### CODE REVIEW

**Comment by dunglas** [comment]
The test failure looks new. Can it be related to the change?

File: frankenphp.go [hunk 1]
```diff
@@ -191,7 +191,7 @@ func NewRequestWithContext(r *http.Request, opts ...RequestOption) (*http.Reques
 	// SCRIPT_FILENAME is the absolute path of SCRIPT_NAME
 	fc.scriptFilename = sanitizedPathJoin(fc.documentRoot, fc.scriptName)
 
-	return r.WithContext(context.WithValue(r.Context(), contextKey, fc)), nil
+	return r.WithContext(context.WithValue(context.Background(), contextKey, fc)), nil
```
Comment (dunglas) [inline frankenphp.go:194]: Couldn't you tweak the context to pass in the Caddy module instead? It may have legit use cases to pass a custom context here.

Comment (withinboredom) [reply frankenphp.go:194]: Moved the PR to WIP as I'm on the tails of a much better solution. It appears we are holding a reference to the Caddy request somehow and that is the crux of the memory leak. Essentially, every request object stays in memory forever and ever in worker mode.

I'm about halfway to narrowing down the leak, but I won't be able to get back to this until at least Wednesday/Thursday.

**Comment by withinboredom** [comment]
This is now ready for review @dunglas

**Comment by dunglas** [comment]
You rock 😍

I'll review ASAP! Don't worry about the CI failure, I'll take care of it.

File: smartpointer.go [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+
+/*
+FrankenPHP is fairly complex because it shuffles handles/requests/contexts
+between C and Go. This simplifies the lifecycle management of per-request
+structures by allowing us to hold references until the end of the request
+and ensure they are always cleaned up.
+*/
+
+// PointerList A list of pointers that can be freed at a later time
+type PointerList struct {
```
Comment (dunglas) [inline smartpointer.go:18]: Can we make this struct internal (lower case p)?

File: smartpointer.go [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+	for _, ptr := range p.Pointers {
+		C.free(ptr)
+	}
+	p.Pointers = nil // To avoid dangling pointers
+}
+
+// FreeAll frees all handles
+func (h *HandleList) FreeAll() {
+	defer func() {
+		if err := recover(); err != nil {
```
Comment (dunglas) [inline smartpointer.go:48]: Why not let it panic so we can catch and fix the issue?

File: smartpointer.go [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+func Pointers() *PointerList {
+	return &PointerList{
+		Pointers: make([]unsafe.Pointer, 0),
+	}
+}
+
+// Handles Get a new list of handles
+func Handles() *HandleList {
+	return &HandleList{
+		Handles: make([]cgo.Handle, 0),
```
Comment (dunglas) [inline smartpointer.go:67]: Micro-optim: we should be able to guess the minimal capacity.

File: smartpointer.go (hunk 3 above)
Comment (withinboredom) [reply smartpointer.go]: That's mostly left in there from hunting down the memory leak and then adapted/refactored into this code because it kinda just made sense. I've removed it.

File: smartpointer.go (hunk 2 above)
Comment (withinboredom) [reply smartpointer.go]: done!

File: smartpointer.go (hunk 3 above)
Comment (withinboredom) [reply smartpointer.go]: Ah, now tests are failing... 👀 into it.

Comment (withinboredom) [reply smartpointer.go]: Ah, I didn't do the micro-optimization correctly. Undid that and just going to leave it since it seems to overcomplicate this a bit.

File: smartpointer.go (hunk 4 above)
Comment (withinboredom) [reply smartpointer.go:62]: Apparently, doing this means we can't use `append()` to add elements and causes a crash ([0] == `nil`, which will panic when it tries to delete the handle.)

**Comment by withinboredom** [comment]
Looks like there is still a leak in cgi-mode, trying to figure out the best way to fix it.

File: smartpointer.go (hunk 4 above)
Comment (dunglas) [reply smartpointer.go:62]: It's the third argument IIRC, not the second.

Comment (withinboredom) [reply smartpointer.go]: oh, nice!

File: frankenphp.go [hunk 5]
```diff
@@ -698,12 +712,23 @@ func ExecuteScriptCLI(script string, args []string) int {
...
+
+	return int(C.frankenphp_execute_script_cli(cScript, argc, (**C.char)(unsafe.Pointer(&argv[0]))))
+}
+
+func convertArgs(args []string) (C.int, []*C.char) {
 	argc := C.int(len(args))
 	argv := make([]*C.char, argc)
 	for i, arg := range args {
 		argv[i] = C.CString(arg)
-		defer C.free(unsafe.Pointer(argv[i]))
```
Comment (withinboredom) [inline frankenphp.go:705]: stumbled across this one by accident. If my IDE warning is correct and I understand correctly, `defer` in a for-loop will actually just call `defer C.free(unsafe.Pointer(argv["last-i"]))` i times.

Comment (dunglas) [reply frankenphp.go:705]: 😭 good one, the typical for loop bug.

**Comment by withinboredom** [comment]
It should be g2g if you're happy with it. The best way to see the memory leak (or lack thereof) is to run k6 with `--no-connection-reuse --no-vu-connection-reuse`, which will eat a couple of gigs of ram in a few mins without this PR.

**Review by dunglas — APPROVED** [review]
Amazing hunt and fix!

**Comment by mathieudz** [comment]
Just letting you know that my memory leak problems are gone too. Try to guess where I restarted my application to run the new version of frankenphp using the heap allocation stats in prometheus :smile: 
image
