### PR TITLE
fix: superglobals-realated crash with custom extensions in worker mode

### LINKED ISSUE #767: `$_SERVER` lifecycle is unsafe in worker mode
### What happened?

Consider the following `worker.php`:

```php
<?php

ignore_user_abort(true);

$_SERVER['MAX_REQUESTS'] ??= 1000;
error_log(print_r($_SERVER, true));

for($nbRequests = 0, $running = true; isset($_SERVER['MAX_REQUESTS']) && ($nbRequests < ((int)$_SERVER['MAX_REQUESTS'])) && $running; ++$nbRequests) {
    error_log(print_r($_SERVER, true));
    $running = \frankenphp_handle_request(static function () {
        echo "Hello World!";
    });
    error_log(print_r($_SERVER, true));
    getopt('abc');
}
```

Running the `worker.php` within `gdb` as:

```
gdb --args ../caddy/frankenphp/frankenphp php-server --worker worker.php
```

and then making a request:

```
curl -v http://localhost/worker.php?some_query_parameters
```

will output:

```
2024/05/06 14:04:52.779 INFO    Array
(
    [HOSTNAME] => c3b166044495
    [SHLVL] => 1
    [HOME] => /root
    [OLDPWD] => /go/src/app
    [GOTOOLCHAIN] => local
    [LOGNAME] => root
    [_] => /usr/bin/gdb
    [TERM] => xterm
    [COLUMNS] => 339
    [PATH] => /go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [CFLAGS] => -ggdb3
    [GOPATH] => /go
    [PHPIZE_DEPS] => autoconf   dpkg-dev        file    g++     gcc     libc-dev        make    pkg-config      re2c
    [PWD] => /go/src/app/testdata
    [LINES] => 96
    [GOLANG_VERSION] => 1.22.2
    [AUTH_TYPE] => 
    [REMOTE_IDENT] => 
    [QUERY_STRING] => 
    [REQUEST_METHOD] => GET
    [REQUEST_URI] => worker.php
    [CONTENT_LENGTH] => 
    [DOCUMENT_ROOT] => /go/src/app/testdata
    [DOCUMENT_URI] => worker.php
    [GATEWAY_INTERFACE] => CGI/1.1
    [HTTP_HOST] => 
    [HTTPS] => 
    [PATH_INFO] => 
    [PHP_SELF] => worker.php
    [REMOTE_ADDR] => 
    [REMOTE_HOST] => 
    [REMOTE_PORT] => 
    [REQUEST_SCHEME] => http
    [SCRIPT_FILENAME] => /go/src/app/testdata/worker.php
    [SCRIPT_NAME] => /worker.php
    [SERVER_NAME] => 
    [SERVER_PORT] => 80
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_SOFTWARE] => FrankenPHP
    [SSL_PROTOCOL] => 
    [FRANKENPHP_WORKER] => 1    {"syslog_level": "notice"}
2024/05/06 14:04:52.779 INFO    FrankenPHP started 🐘   {"php_version": "8.3.8-dev"}
2024/05/06 14:04:52.780 INFO    Caddy serving PHP app on :80
2024/05/06 14:04:52.790 WARN    tls     storage cleaning happened too recently; skipping for now        {"storage": "FileStorage:/root/.local/share/caddy", "instance": "61794d2e-90a3-449d-8ea5-842c5e837ac7", "try_again": "2024/05/07 14:04:52.790", "try_again_in": 86399.999999544}
2024/05/06 14:04:52.790 INFO    tls     finished cleaning storage units
2024/05/06 14:04:58.884 INFO    Array
(
    [HOSTNAME] => c3b166044495
    [SHLVL] => 1
    [HOME] => /root
    [OLDPWD] => /go/src/app
    [GOTOOLCHAIN] => local
    [LOGNAME] => root
    [_] => /usr/bin/gdb
    [TERM] => xterm
    [COLUMNS] => 339
    [PATH] => /go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [CFLAGS] => -ggdb3
    [GOPATH] => /go
    [PHPIZE_DEPS] => autoconf   dpkg-dev        file    g++     gcc     libc-dev        make    pkg-config      re2c
    [PWD] => /go/src/app/testdata
    [LINES] => 96
    [GOLANG_VERSION] => 1.22.2
    [AUTH_TYPE] => 
    [REMOTE_IDENT] => 
    [QUERY_STRING] => some_query_parameters
    [REQUEST_METHOD] => GET
    [REQUEST_URI] => /worker.php?some_query_parameters
    [CONTENT_LENGTH] => 
    [DOCUMENT_ROOT] => /go/src/app/testdata
    [DOCUMENT_URI] => worker.php
    [GATEWAY_INTERFACE] => CGI/1.1
    [HTTP_HOST] => localhost
    [HTTPS] => 
    [PATH_INFO] => 
    [PHP_SELF] => worker.php
    [REMOTE_ADDR] => 127.0.0.1
    [REMOTE_HOST] => 127.0.0.1
    [REMOTE_PORT] => 38618
    [REQUEST_SCHEME] => http
    [SCRIPT_FILENAME] => /go/src/app/testdata/worker.php
    [SCRIPT_NAME] => /worker.php
    [SERVER_NAME] => localhost
    [SERVER_PORT] => 80
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_SOFTWARE] => FrankenPHP
    [SSL_PROTOCOL] => 
    [HTTP_USER_AGENT] => curl/7.88.1
    [HTTP_ACCEPT] => */*
    [REQUEST_TIME_FLOAT] => 1715004298.8845
    [REQUEST_TIME] => 1715004298
)
        {"syslog_level": "notice"}

Thread 16 "thpool-0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff81ffb6c0 (LWP 802)]
0x00007ffff73485f4 in _zend_is_inconsistent (ht=0x0, file=0x7ffff7d71548 "/usr/local/src/php/Zend/zend_hash.c", line=2681) at /usr/local/src/php/Zend/zend_hash.c:57
57              if ((HT_FLAGS(ht) & HASH_FLAG_CONSISTENCY) == HT_OK) {
(gdb) bt
#0  0x00007ffff73485f4 in _zend_is_inconsistent (ht=0x0, file=0x7ffff7d71548 "/usr/local/src/php/Zend/zend_hash.c", line=2681) at /usr/local/src/php/Zend/zend_hash.c:57
#1  0x00007ffff7351600 in zend_hash_find_known_hash (ht=0x0, key=0x7fff60202980) at /usr/local/src/php/Zend/zend_hash.c:2681
#2  0x00007ffff717eb62 in zend_hash_find_ex (ht=0x0, key=0x7fff60202980, known_hash=true) at /usr/local/src/php/Zend/zend_hash.h:188
#3  0x00007ffff717ec78 in zend_hash_find_ex_ind (ht=0x0, key=0x7fff60202980, known_hash=true) at /usr/local/src/php/Zend/zend_hash.h:427
#4  0x00007ffff71857f8 in zif_getopt (execute_data=0x7fff804150c0, return_value=0x7fff81ff9410) at /usr/local/src/php/ext/standard/basic_functions.c:979
#5  0x00007ffff7377773 in ZEND_DO_ICALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/local/src/php/Zend/zend_vm_execute.h:1275
#6  0x00007ffff73faa64 in execute_ex (ex=0x7fff80415020) at /usr/local/src/php/Zend/zend_vm_execute.h:57212
#7  0x00007ffff73ff357 in zend_execute (op_array=0x7fff80477000, return_value=0x0) at /usr/local/src/php/Zend/zend_vm_execute.h:61604
#8  0x00007ffff7332f07 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/local/src/php/Zend/zend.c:1891
#9  0x00007ffff726bb0c in php_execute_script (primary_file=0x7fff81ffaa90) at /usr/local/src/php/main/main.c:2515
#10 0x00000000017eb2d9 in frankenphp_execute_script (file_name=0x0) at frankenphp.c:851
#11 0x00000000017e8977 in _cgo_b7d6fd74a0c8_Cfunc_frankenphp_execute_script (v=0xc000805dd8) at /tmp/go-build/cgo-gcc-prolog:55
#12 0x000000000047e764 in runtime.asmcgocall () at /usr/local/go/src/runtime/asm_amd64.s:918
#13 0x000000c000800700 in ?? ()
#14 0x00007fff81ffac00 in ?? ()
#15 0x0000000000000000 in ?? ()
```

------------

Note the following:

1. To userland code `$_SERVER` variable will preserve its request-specific contents after `frankenphp_handle_request` returns. This might or might not be intended. To the developer it might be a gotcha, because they might expect the request callback to be sandboxed and not affect the logic outside of it. I did not see anything about this in the documentation.

2. To internal code, the `$_SERVER` variable will be unavailable after the first call to `frankenphp_handle_request`, because the `PG(http_globals)` are cleared in `frankenphp_request_reset()`. This makes it unsafe to call any internal function that relies on superglobals, as demonstrated by the call to `getopt()`:

https://github.com/php/php-src/blob/55966f098b23fe34a526d64f984c191bdc53b1e7/ext/standard/basic_functions.c#L953-L956

------------

For the fix, I don't have a strong preference whether `$_SERVER` before `frankenphp_handle_request` should be identical to `$_SERVER` after `frankenphp_handle_request`, or whether the request-specific data should be preserved in `$_SERVER` as it is the case. I believe it should be documented, though. Furthermore the view for internal functions should be consistent with the userland view, i.e. calling internal functions relying on `$_SERVER` should not lead to a crash and observe the same contents for the array.

### Build Type

`dev.Dockerfile`

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

`dev.Dockerfile` without any config changes.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dunglas**
Closes #767.
Partial fix for #592 (memory leak when dealing with cookies in worker mode).

### CODE REVIEW

**Comment by dunglas** [comment]
@withinboredom @TimWolla would you mind reviewing the proposed fix?

I need to do more testing to ensure that the behavior is what is expected, but at least this fixes the segfault. We'll have to double-check if this doesn't introduce a memory leak or some weird issues.

File: frankenphp.c [hunk 1]
```diff
@@ -69,6 +69,7 @@ typedef struct frankenphp_server_context {
   uintptr_t current_request;
   uintptr_t main_request;
   bool worker_ready;
+  zval **worker_http_globals;
```
Comment (TimWolla) [inline frankenphp.c:72]:
```suggestion
  zval *worker_http_globals;
```

File: frankenphp.c [hunk 2]
```diff
@@ -105,13 +106,23 @@ static uintptr_t frankenphp_clean_server_context() {
...
+        zval_ptr_dtor(&PG(http_globals)[i]);
+      }
 
-    memset(&PG(http_globals), 0, sizeof(zval) * NUM_TRACK_VARS);
+      // Restore worker script super globals
+      memcpy(&PG(http_globals), ctx->worker_http_globals,
+             sizeof(zval) * NUM_TRACK_VARS);
+      php_hash_environment();
+    } else {
+      ctx->worker_http_globals = (zval **)malloc(sizeof(zval) * NUM_TRACK_VARS);
```
Comment (TimWolla) [inline frankenphp.c:122]: Casting the return value of `malloc()` is not necessary in C. In this case it luckily pointed out the incorrect type of `worker_http_globals`, though.

File: frankenphp.c [hunk 3]
```diff
@@ -105,13 +106,23 @@ static uintptr_t frankenphp_clean_server_context() {
...
+      memcpy(ctx->worker_http_globals, &PG(http_globals),
+             sizeof(zval) * NUM_TRACK_VARS);
```
Comment (TimWolla) [inline frankenphp.c:124]: And here it probably should be this (untested):
```suggestion
      memcpy(ctx->worker_http_globals, PG(http_globals),
             sizeof(zval) * NUM_TRACK_VARS);
```

**Review by TimWolla — COMMENTED** [review]
> I need to do more testing to ensure that the behavior is what is expected, but at least this fixes the segfault. We'll have to double-check if this doesn't introduce a memory leak or some weird issues.

It does leak:

```
[Tue May 21 07:27:50 2024]  Script:  '-'
/usr/local/src/php/Zend/zend_string.h(174) :  Freeing 0x00007fff802020a0 (40 bytes), script=-
Last leak repeated 14 times
[Tue May 21 07:27:50 2024]  Script:  '-'
/usr/local/src/php/Zend/zend_string.h(174) :  Freeing 0x00007fff802020f0 (40 bytes), script=-
Last leak repeated 42 times
[Tue May 21 07:27:50 2024]  Script:  '-'
/usr/local/src/php/Zend/zend_string.h(174) :  Freeing 0x00007fff802025a0 (40 bytes), script=-
Last leak repeated 12 times
[Tue May 21 07:27:50 2024]  Script:  '-'
/usr/local/src/php/Zend/zend_hash.c(291) :  Freeing 0x00007fff8025f000 (56 bytes), script=-
Last leak repeated 4 times
[Tue May 21 07:27:50 2024]  Script:  '-'
/usr/local/src/php/Zend/zend_hash.c(1311) :  Freeing 0x00007fff80260c00 (2560 bytes), script=-
=== Total 77 memory leaks detected ===
```

For debugging memory leaks, I suggest `USE_ZEND_ALLOC=0` + ASAN. Valgrind does not appear to work well here.

I'm also seeing 

```
2024/05/21 07:27:50.165 INFO    restarting      {"worker": "/go/src/app/testdata/worker.php"}
```

immediately after, but I'm not sure if that is expected.

The following test script also appears to log the incorrect information:

```
<?php

ignore_user_abort(true);

for($running = true; $running;) {
    file_put_contents(__DIR__ . '/log', "before: " . $_SERVER['REQUEST_URI'] . ' ' . $_SERVER['REMOTE_ADDR'] . "\n", FILE_APPEND);

    $running = \frankenphp_handle_request(static function () {
        file_put_contents(__DIR__ . '/log', "inside: " . $_SERVER['REQUEST_URI'] . ' ' . $_SERVER['REMOTE_ADDR'] . "\n", FILE_APPEND);
    });

    file_put_contents(__DIR__ . '/log', "after : " . $_SERVER['REQUEST_URI'] . ' ' . $_SERVER['REMOTE_ADDR'] . "\n", FILE_APPEND);
}
```

I would expected `before:` and `after:` to look identical at all times, but I'm seeing:

```
before: worker.php 
before: worker.php 
before: worker.php 
before: worker.php 
inside: /worker.php?some_query_parameters 127.0.0.1
after : /worker.php?some_query_parameters 127.0.0.1
before: /worker.php?some_query_parameters 127.0.0.1
inside: /worker.php?some_query_parameters 127.0.0.1
after : /worker.php?some_query_parameters 127.0.0.1
before: /worker.php?some_query_parameters 127.0.0.1
```

**Comment by TimWolla** [comment]
> Valgrind does not appear to work well here.

I does point out some conditional jumps that depend on uninitialized in non-go code values, though. But also quite a few invalid reads in go code, which might or might not be expected.

**Comment by TimWolla** [comment]
> The following test script also appears to log the incorrect information:

The cause probably is that you can't naively `memcpy` the zval, because the reference counting of strings is then incorrect, allowing the code to perform in-place modification instead of doing copy-on-write. I didn't test, because I find the DX of the development container to be pretty unwieldy.

**Comment by dunglas** [comment]
Thanks for your detailed review @TimWolla. Regarding the Docker container, it is entirely optional. When you have a local installation of PHP, you can just run this command to compile the binary: https://frankenphp.dev/docs/compile/#compile-the-go-app

File: frankenphp.c [hunk 4]
```diff
@@ -105,13 +106,23 @@ static uintptr_t frankenphp_clean_server_context() {
...
-    }
+    if (ctx->worker_ready) {
+      int i;
+      for (i = 0; i < NUM_TRACK_VARS; i++) {
+        zval_ptr_dtor(&PG(http_globals)[i]);
+      }
 
-    memset(&PG(http_globals), 0, sizeof(zval) * NUM_TRACK_VARS);
+      // Restore worker script super globals
+      memcpy(&PG(http_globals), ctx->worker_http_globals,
```
Comment (withinboredom) [inline frankenphp.c:118]: Pretty sure this will break GC since reference counting won't be performed and may either cause a memory leak or GC'ing of variables unexpectedly.

What you probably (maybe) want to do is create a hashmap copy of globals before starting the work, then after the work, restore that hashmap to globals

**Comment by dunglas** [comment]
I pushed a new version that uses `ZVAL_COPY` as suggested by @TimWolla. This should fix the leak (to be double-checked).

This behaves almost as expected but I identified two issues:

* [ ] `$_SERVER['FRANKENPHP_WORKER']` and probably other custom environment variables passed to the worker script are lost inside the closure. We should probably merge the variables from the worker script in the closure to prevent this issue.
* [ ] `$_SERVER['FRANKENPHP_WORKER']`  is NULL terminated, that's an existing, unrelated bug. I'll fix ti.

**Comment by dunglas** [comment]
The behavior is now the expected one. If you don't mind, cloud you please review again?

**Comment by dunglas** [comment]
Actually, merging the $_SERVER superglobals of the worker and the request wasn't expected, we even have a test (the failing one) for that.

As showcased by the test, it's entirely possible to do that userland if needed.

Should we keep the existing behavior of not merging (after a second thought, I think that it's more flexible to not merge)?

**Comment by TimWolla** [comment]
I'm still seeing a leak:

```
b57e622520ad# ../caddy/frankenphp/frankenphp php-server --worker worker-getopt.php
2024/05/22 13:44:51.696 WARN    admin   admin endpoint disabled
2024/05/22 13:44:51.696 WARN    http.auto_https server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server {"server_name": "php", "http_port": 80}
2024/05/22 13:44:51.696 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc000345a80"}
2024/05/22 13:44:51.713 INFO    FrankenPHP started 🐘   {"php_version": "8.3.8-dev"}
2024/05/22 13:44:51.714 INFO    http.log        server running  {"name": "php", "protocols": ["h1", "h2", "h3"]}
2024/05/22 13:44:51.714 INFO    Caddy serving PHP app on :80
2024/05/22 13:44:51.723 WARN    tls     storage cleaning happened too recently; skipping for now        {"storage": "FileStorage:/root/.local/share/caddy", "instance": "00d35d99-1901-4bf0-aa0b-e1f662db2acd", "try_again": "2024/05/23 13:44:51.723", "try_again_in": 86399.999999265}
2024/05/22 13:44:51.723 INFO    tls     finished cleaning storage units
[Wed May 22 13:44:53 2024]  Script:  '-'
/usr/local/src/php/Zend/zend_string.h(174) :  Freeing 0x00007fe08c2021e0 (40 bytes), script=-
Last leak repeated 12 times
[Wed May 22 13:44:53 2024]  Script:  '-'
/usr/local/src/php/Zend/zend_string.h(174) :  Freeing 0x00007fe08c202230 (40 bytes), script=-
Last leak repeated 40 times
[Wed May 22 13:44:53 2024]  Script:  '-'
/usr/local/src/php/Zend/zend_string.h(174) :  Freeing 0x00007fe08c2026e0 (48 bytes), script=-
Last leak repeated 12 times
[Wed May 22 13:44:53 2024]  Script:  '-'
/usr/local/src/php/Zend/zend_hash.c(291) :  Freeing 0x00007fe08c25f000 (56 bytes), script=-
Last leak repeated 4 times
[Wed May 22 13:44:53 2024]  Script:  '-'
/usr/local/src/php/Zend/zend_hash.c(1311) :  Freeing 0x00007fe08c260c00 (2560 bytes), script=-
=== Total 73 memory leaks detected ===
2024/05/22 13:44:53.542 ERROR   unexpected termination, restarting      {"worker": "/go/src/app/testdata/worker-getopt.php", "exit_status": 2}
```

and then calling `curl -v http://localhost/worker-getopt.php?some_query_parameters`.

I also might've done something wrong while starting FrankenPHP, because of the `exit(2)` being triggered.

**Comment by TimWolla** [comment]
And the test script with the `file_put_contents` from yesterday’s review still outputs the wrong data for the `after:`.

**Comment by dunglas** [comment]
I've an idea for the `after:`. I'll take a look. The crash and the leak are weird, I'm not sure of why it behaves like this.

**Comment by dunglas** [comment]
Maybe related: https://github.com/dunglas/frankenphp/pull/81

File: frankenphp.c [hunk 5]
```diff
@@ -105,13 +106,24 @@ static uintptr_t frankenphp_clean_server_context() {
...
+    if (ctx->worker_ready) {
+      for (i = 0; i < NUM_TRACK_VARS; i++) {
+        zval_ptr_dtor(&PG(http_globals)[i]);
+      }
 
-    for (i = 0; i < NUM_TRACK_VARS; i++) {
-      zval_ptr_dtor(&PG(http_globals)[i]);
+      // Restore worker script super globals
+      for (i = 0; i < NUM_TRACK_VARS; i++) {
+        ZVAL_COPY(&PG(http_globals)[i], &ctx->worker_http_globals[i]);
```
Comment (withinboredom) [inline frankenphp.c:119]: You may have to call `GC_DEREF(&PG(http_globals)[i])` here to prevent a memory leak. I think. 

This is because you've increased the references here +1, but in `php_has_environment()` the ref will also increase +1. (IIRC) So you need to manually decrease it -1.

Comment (withinboredom) [reply frankenphp.c:119]: or `GC_DEREF(&ctx->worker_http_global[i])`, :D

Comment (TimWolla) [reply frankenphp.c:119]: If that's the problem, `ZVAL_COPY_VALUE` will copy the value, without increasing the reference count. But then `memcpy` should also have worked.

Comment (withinboredom) [reply frankenphp.c:119]: I believe it may be only needed in this if-branch.

Comment (dunglas) [reply frankenphp.c]: I "fixed" the leak but as you can see the fix is bad, there is a logic error somewhere :D

**Comment by dunglas** [comment]
@TimWolla @withinboredom would you mind testing/reviewing thi patch one more time? The current implementation looks ok-ish to me.

**Comment by TimWolla** [comment]
@dunglas For the test script in https://github.com/dunglas/frankenphp/pull/796#pullrequestreview-2067722841 I'm still seeing the wrong data being written to the `log` file:

```
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
before: worker-getopt.php 
inside: /worker-getopt.php?some_query_parameters 127.0.0.1
after : /worker-getopt.php?some_query_parameters 127.0.0.1
before: /worker-getopt.php?some_query_parameters 127.0.0.1
```

File: frankenphp.c [hunk 6]
```diff
@@ -105,13 +106,23 @@ static uintptr_t frankenphp_clean_server_context() {
...
   zend_try {
+    frankenphp_server_context *ctx = SG(server_context);
+
     int i;
+    if (ctx->worker_ready) {
+      // Restore worker script super globals
+      for (i = 0; i < NUM_TRACK_VARS; i++) {
+        zval_ptr_dtor(&PG(http_globals)[i]);
+      }
+      memcpy(&PG(http_globals), &ctx->worker_http_globals,
```
Comment (dunglas) [inline frankenphp.c:117]: This doesn't work because `php_hash_environment()` clears `PG(http_globals)`): https://github.com/php/php-src/blob/62cdaac2806ba0a9f3443508ba60a6f552ef6bce/main/php_variables.c#L787

File: frankenphp.c [hunk 7]
```diff
@@ -105,13 +106,23 @@ static uintptr_t frankenphp_clean_server_context() {
...
+             sizeof(zval) * NUM_TRACK_VARS);
 
-    for (i = 0; i < NUM_TRACK_VARS; i++) {
-      zval_ptr_dtor(&PG(http_globals)[i]);
+      php_hash_environment();
```
Comment (dunglas) [inline frankenphp.c:120]: For this to work, we need to save and restore the `SG(request_info)` of the worker script, but I wonder if it is worth it. Resetting the whole context as in the beginning of the script will be costly and useless. After all, maybe should we keep the current behavior and keep the context of the previous request until the next one is handled.

WDYT @withinboredom @TimWolla?

**Comment by dunglas** [comment]
In the last commit, I fixed the crash without changing the existing behavior (the docs change is now irrelevant, I'll revert that). I think it's good enough for now.

File: frankenphp.c (hunk 7 above)
Comment (TimWolla) [reply frankenphp.c]: As I'm mentioned in the issue I created, I don’t have an opinion here. That depends on what you believe your users expectations are.

**Comment by TimWolla** [comment]
> In the last commit, I fixed the crash without changing the existing behavior (the docs change is now irrelevant, I'll revert that). I think it's good enough for now.

I can confirm the crash is fixed, but internal functions see an empty `$_SERVER` now. That's certainly better than a crash, but would still be inconsistent with userland’s PoV.

File: frankenphp.c (hunk 7 above)
Comment (withinboredom) [reply frankenphp.c]: That's a tricky one. Personally, I use the last context to run logging things (treblle specifically) before continuing to the next request so I would find it useful. I can't think of why you would not want the last request's context.

File: frankenphp.c [hunk 8]
```diff
@@ -73,11 +73,11 @@ typedef struct frankenphp_server_context {
...
 } frankenphp_server_context;
 
-static uintptr_t frankenphp_clean_server_context() {
+static void frankenphp_free_request_context() {
   frankenphp_server_context *ctx = SG(server_context);
-  if (ctx == NULL) {
-    return 0;
-  }
+
+  free(ctx->cookie_data);
```
Comment (dunglas) [inline frankenphp.c:79]: Moving this `free()` here likely fix a memory leak in worker mode.

**Comment by dunglas** [comment]
I cleaned the code and updated the docs. I think I've found a way to keep the userland and internal structures in sync but I didn't create a test case. @TimWolla would you mind checking if this now works with the Tideways extension?

**Comment by TimWolla** [comment]
> I think I've found a way to keep the userland and internal structures in sync but I didn't create a test case.

I can confirm that internal functions called after `frankenphp_handle_request()` see the same `$_SERVER` as userland *initially* saw.

However what is not kept in sync is manually writing to `$_SERVER` either within the callback or after `frankenphp_handle_request()` finishes and before calling the internal function.

```php
$_SERVER['dummy'] = 'value';
```

Dumping `var_dump(count($_SERVER))` returns `42` in my test case, but an internal function
 
```c
ZEND_FUNCTION(native_debug)
{
    zend_is_auto_global(ZSTR_KNOWN(ZEND_STR_AUTOGLOBAL_SERVER));
    HashTable *server = Z_ARRVAL_P(&PG(http_globals)[TRACK_VARS_SERVER]);
    printf("%d\n", zend_hash_num_elements(server));
    zval *request_uri = zend_hash_str_find(server, "REQUEST_URI", strlen("REQUEST_URI"));
    printf("%s\n", Z_STRVAL_P(request_uri));
}
```
prints 41 (because `dummy` is missing). Likewise modifying an entry using:

```php
$_SERVER['REQUEST_URI'] = 'dummy';
```

is not visible to the native function.

---------------

I'm not sure if as a user I would prefer a crash or silently incorrect data. Your call.

**Comment by dunglas** [comment]
@TimWolla are the two data structures synced automatically in a normal script? I may be wrong, but I don't think that we do anything special FrankenPHP-side that would cause this desync.

**Comment by dunglas** [comment]
@TimWolla according to my tests, this behaves the same even when not in worker mode, so it looks "expected" to me, at least let's say that it's not related to FrankenPHP.

**Comment by TimWolla** [comment]
@dunglas Can confirm with the cli-server. Sorry for the confusion. This looks good to me then!

**Review by TimWolla — APPROVED** [review]
