### PR TITLE
fix(metrics): handle the case where the worker is already assigned to a thread

### LINKED ISSUE #1163: frankenphp_worker_php_ready_worker is skewing to negative values with worker restarts
### What happened?

Hi.

We have excitingly been trying out the new 1.3.0 release. We immediately setup an alert on the `frankenphp_worker_php_ready_worker` metric on our environments.

We however observed that this metric has a decreasing pattern to it, that is not equal to the relationship of `total_workers - busy_workers`.

Look at this plot of the metric of a somewhat busy container (20RPS ish) (each line is a seperate container)

image

I was very worried of this metric, however it has now become a negative value, indicating that is keep decreasing even below 0. In our case we may see the ready_worker metric report -2, while the busy worker metric is 4 and total workers is 60. So in this case I assume the correct value is 56? Or close to 56.

It looks to be somewhat correlated to worker restarts, looking at this graph: 

image

The service is responding as normal even with negative ready workers

### Build Type

Docker (Debian Bookworm)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Not relevant
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by withinboredom**
fixes #1163 

There are also some miscellaneous fixes in here as well.

1. I noticed that using the watcher introduced race conditions with the "ready waitgroup"
2. I removed atomics and tried to wrap my head around what was going on
3. I discovered #1172 
4. Instead of a WG, I used a channel to avoid race conditions and is also much simpler to reason about.
5. I found a potential memory leak when a worker restarts

cc: @AlliBalliBaba

### CODE REVIEW

**Comment by withinboredom** [comment]
Strange that tests are failing, they aren't failing locally.

**Comment by withinboredom** [comment]
Yep, this is indeed the case. Compiling with the watcher causes the tests to be non-deterministic. I'll investigate.

**Comment by withinboredom** [comment]
There's still some issues remaining with this metric:

When a worker restarts, the original thread is given to the "cgi pool" and a new worker is instantiated from "cgi pool" which may-or-may-not be the same as the previous thread. This will cause this metric to eventually be increased to the total number of php threads.

**Review by dunglas — APPROVED** [review]

File: worker.go [hunk 1]
```diff
@@ -343,5 +352,14 @@ func go_frankenphp_finish_request(threadIndex C.uintptr_t, isWorkerRequest bool)
...
 		thread.Unpin()
+		workers[fc.scriptFilename].threadMutex.Lock()
+		defer workers[fc.scriptFilename].threadMutex.Unlock()
+		for i, t := range workers[fc.scriptFilename].threads {
+			if t == thread {
+				// remove thread from worker threads
+				workers[fc.scriptFilename].threads = append(workers[fc.scriptFilename].threads[:i], workers[fc.scriptFilename].threads[i+1:]...)
+				break
+			}
+		}
```
Comment (AlliBalliBaba) [inline worker.go:363]: I probably doesn't make sense to remove the thread from the worker after each request. Did you mean to put this logic at the end of the worker script?

Leaving this here will break `worker.handleRequest` since you're destroying the thread's request chan after each request.

File: worker.go [hunk 2]
```diff
@@ -95,14 +95,14 @@ func (worker *worker) startNewWorkerThread() {
...
 	for {
-
 		// if the worker can stay up longer than backoff*2, it is probably an application error
 		upFunc := sync.Once{}
 		go func() {
 			backingOffLock.RLock()
 			wait := backoff * 2
 			backingOffLock.RUnlock()
 			time.Sleep(wait)
+			worker.ready <- struct{}{}
```
Comment (AlliBalliBaba) [inline worker.go:105]: I'm not sure if this is the correct approach. What if the worker script takes longer than 200ms to start and then fails? Additionally, this will unnecessarily delay startup in most cases.
This line should probably be moved somewhere to `metrics.ReadyWorker`, right after `frankenphp_handle_request()` was called.

File: worker.go [hunk 3]
```diff
@@ -32,34 +32,28 @@ const maxWorkerConsecutiveFailures = 6
...
 		worker.threads = make([]*phpThread, 0, o.num)
 		if err != nil {
 			return err
 		}
-		workersReadyWG.Add(worker.num)
 		for i := 0; i < worker.num; i++ {
 			go worker.startNewWorkerThread()
 		}
+		for i := 0; i < worker.num; i++ {
+			<-worker.ready
```
Comment (AlliBalliBaba) [inline worker.go:53]: What is the advantage of using a chan instead of a WaitGroup here? With the previous logic multiple worker scripts were able to start their threads in parallel, now they have to start sequentially.

**Review by AlliBalliBaba — CHANGES_REQUESTED** [review]

**Comment by AlliBalliBaba** [comment]
#1137 indeed addresses the issue with worker threads turning into regular threads. There'll probably be a lot of merge conflicts with this PR

File: worker.go (hunk 1 above)
Comment (withinboredom) [reply worker.go:363]: In my tests, this is only reached when the worker request (ie, the worker script) ends. We're only removing the thread from the list of active threads because it will not be reused (and in fact, "lost") after this function ends. This is the last chance to remove it from the slice.

Comment (AlliBalliBaba) [reply worker.go:363]: This function is called after each worker request (`frankenphp_handle_request`), not at the end of the worker script. You can confirm this by just adding a log here `logger.Warn("worker request over")`

File: worker.go (hunk 3 above)
Comment (withinboredom) [reply worker.go:53]: > What is the advantage of using a chan instead of a WaitGroup here?

There are significant issues with using a WaitGroup. A WaitGroup makes sense if everything happened exactly once, but workers can be restarted, shutdown, migrate between threads, and any number of 'things.' These all basically prevent a WaitGroup from making sense. Using a channel is much easier to simply wait for them all to become available.

> With the previous logic multiple worker scripts were able to start their threads in parallel, now they have to start sequentially.

They still start in parallel. There's a loop somewhere in any implementation. In this case, it is in the application instead of a semaphore. In fact, this is basically a semaphore, which Go doesn't have.

**Comment by withinboredom** [comment]
@AlliBalliBaba, I don't see any requested changes?

File: worker.go (hunk 2 above)
Comment (AlliBalliBaba) [reply worker.go]: Currently it will definitely wait for all threads to be ready via the `workersReadyWG`, which only reaches 0 after each thread has called `frankenphp_handle_request()`. With this implementation we could reach a 'ready' state even if the worker script doesn't contain `frankenphp_handle_request()`
I guess it depends on when you would consider the worker thread to be 'ready', but why go with 'reasonable confidence' when you can have absolute confidence instead? (and be faster in most cases)

File: worker.go (hunk 3 above)
Comment (AlliBalliBaba) [reply worker.go:53]: > There are significant issues with using a WaitGroup. A WaitGroup makes sense if everything happened exactly once, but workers can be restarted, shutdown, migrate between threads, and any number of 'things.' These all basically prevent a WaitGroup from making sense. Using a channel is much easier to simply wait for them all to become available.

I agree with you, in #1137 I also removed this specific WaitGroup. I guess it just doesn't make sense in the current implementation, since workers do indeed only start once.

> They still start in parallel. There's a loop somewhere in any implementation. In this case, it is in the application instead of a semaphore. In fact, this is basically a semaphore, which Go doesn't expose to developers.

They are starting in parallel for 1 worker script. What I meant is, they don't start in parallel for multiple worker scripts anymore.

File: worker.go (hunk 1 above)
Comment (withinboredom) [reply worker.go:366]: I see. Hmmm, I'll have to dig into it a bit deeper. Right now, there is a memory leak:

image

As you can see, the number of threads that belong to a worker grow unbounded, despite there only supposed to be a single thread for this worker (see: `num = 1`)

File: worker.go (hunk 2 above)
Comment (withinboredom) [reply worker.go]: > Currently it will definitely wait for all threads to be ready via the workersReadyWG, which only reaches 0 after each thread has called frankenphp_handle_request(). 

I honestly don't remember what I ran into last night that specifically triggered this rabbit hole, other than turning on the watcher caused all kinds of problems with the metrics being output. TL;DR: I was just trying to simplify things to understand _why_ it is causing issues, then running into other issues as I went, yak shaving my way through it all.

I ran into a number of minor issues that sometimes made it past the atomics, like restarting during shutdown. Atomics are terrible unless you are using CAS, and you are not guaranteed to get the latest value ... so I deleted them. From there, it was just figuring out what was going wrong with the `WorkersReadyWG` because as mentioned, the current architecture doesn't really make sense for them, but we don't want to run tests until workers are started.

So, most of the refactoring is just in getting rid of atomics. This then uncovered new failing tests 100% of the time instead of randomly, particularly when restarting workers... and so on.

After all this, I still don't know why watchers specifically caused my issues 😆

File: worker.go (hunk 1 above)
Comment (withinboredom) [reply worker.go:366]: In all honesty, I don't believe this can be fixed until #1137.

File: worker.go (hunk 2 above)
Comment (AlliBalliBaba) [reply worker.go]: Yeah I originally intended my refactor PR to just be a small step towards more control over PHP threads. But then I realized it could potentially also fix Fibers and it kinda ended up doing more than I wanted it to. 
Problem with these big PRs is that they kind of block other PRs (like this one).

Comment (withinboredom) [reply worker.go]: Maybe we should take smaller steps in our PR. Unfortunately, I never did figure out what was broken here, short of refactoring the entire worker stuff. :(

It might be worth working on an actual design in a Discussion? That way we'd be able to work on different parts independently and break it down into smaller PRs. Maybe we could take a 'strangler fig' approach and reimplement it separate from the current codebase. So, we could just use build tags to switch between worker implementations (at least while we are working on it), and people could test it more easily.

Comment (withinboredom) [reply worker.go]: https://github.com/dunglas/frankenphp/discussions/1175

**Review by AlliBalliBaba — APPROVED** [review]

**Review by dunglas — APPROVED** [review]
