### PR TITLE
fix relative paths not being resolved correctly by spc

### LINKED ISSUE #2092: Unable to build static binary with relative path
### What happened?

Since the v1.10.0 I cannot build a static binary if the value of `EMBED` env variable is a relative path.

I guess the test with `-n` option doesn't work with relative folder path.
https://github.com/php/frankenphp/blob/c6cadf3bf66be6658552bbeacf1d845b2e249478/build-static.sh#L180

Here's a sample working with v1.9.0:
```Dockerfile
FROM --platform=linux/amd64 dunglas/frankenphp:static-builder-gnu-1.9

# Copy your app
WORKDIR /go/src/app/dist/app
COPY . .

# Build the static binary
WORKDIR /go/src/app/
RUN EMBED=dist/app/ ./build-static.sh
```

Since v1.10.0, I have to pass an absolute path to `EMBED` otherwise the binary doesn't include the content of my app:
```Dockerfile
FROM --platform=linux/amd64 dunglas/frankenphp:static-builder-gnu-1.10

# Copy your app
WORKDIR /go/src/app/dist/app
COPY . .

# Build the static binary
WORKDIR /go/src/app/
RUN EMBED=/go/src/app/dist/app ./build-static.sh
```

### Build Type

Static binary

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Docker image: dunglas/frankenphp:static-builder-gnu
Static parameters:
PHP_EXTENSIONS=amqp,brotli,bz2,ctype,curl,dom,fileinfo,filter,iconv,intl,ldap,libxml,lz4,pdo_sqlite,session,sodium,sqlite3,ssh2,tokenizer,xml,xmlreader,xmlwriter,xz,zip,zlib,zstd
```

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by henderkes**
closes #2092
closes #2064

### CODE REVIEW

File: build-static.sh [hunk 1]
```diff
@@ -178,7 +178,15 @@ fi
 
 # Embed PHP app, if any
 if [ -n "${EMBED}" ] && [ -d "${EMBED}" ]; then
-	SPC_OPT_BUILD_ARGS="${SPC_OPT_BUILD_ARGS} --with-frankenphp-app=${EMBED}"
+	case "${EMBED}" in
```
Comment (dunglas) [inline build-static.sh]: Maybe can we simplify by overwriting `EMBED` if it's an absolute path?
