### PR TITLE
fix(worker): initialize _request in worker mode with auto_globals

### LINKED ISSUE #1931: In worker mode, $_REQUEST is incorrectly cached
### What happened?

Laravel Octance
Configure the following a simple routes in Laravel：

```
Route::get('/test', function () {
    $foo = $_REQUEST['foo'] ?? 'null';
    return $foo;
});
```

The php.ini item:
auto_globals_jit = On // Default Configuration

1、Go to http://127.0.0.1:8000/test?foo=test1 //echo test1
2、Go to http://127.0.0.1:8000/test?foo=test2 //echo test1

But $_GET/$_POST is work.

When php.ini：
auto_globals_jit = Off

1、Go to http://127.0.0.1:8000/test?foo=test1 //echo test1
2、Go to http://127.0.0.1:8000/test?foo=test2 //echo test2

$_REQUEST is work.

### Build Type

Docker (Debian Bookworm)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
auto_globals_jit = On
```

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by xavierleune**
Hi,

This PR fixes #1931, it handles $_REQUEST in worker mode correctly when `auto_globals_jit` is enabled (default configuration for PHP).
Some concerns were raised in the comments of the issue regarding performance. This implementation should make sure that request is created only if used.

However if a previous execution plan already used `_REQUEST`, all subsequent requests will create it. So the concern is "kindof" mitigated.

Let me know if you have any suggestion to improve this.

### CODE REVIEW

File: testdata/request-superglobal-conditional-include.php [hunk 1]
```diff
@@ -0,0 +1,20 @@
+<?php
+// This file tests if $_REQUEST is properly re-initialized in worker mode
+// The key test is: does $_REQUEST contain ONLY the current request's data?
+
+// Static counter to track how many times this file is executed (not compiled)
+static $execCount = 0;
+$execCount++;
+
+echo "EXEC_COUNT:" . $execCount;
```
[the remark this answers is not in the document]
Comment (xavierleune) [reply testdata/request-superglobal-conditional-include.php:9]: will ignore that one

**Comment by xavierleune** [comment]
Is the failing test the kind of situation where we should try turning it off and on again ? :D

File: frankenphp.c [hunk 2]
```diff
@@ -126,13 +126,18 @@ static void frankenphp_reset_super_globals() {
...
-       */
+      /* JIT globals ($_REQUEST, $GLOBALS) need special handling:
+       * - If in symbol_table: re-initialize with current request data
+       * - If not: re-arm for potential future use during include */
+      if (zend_hash_exists(&EG(symbol_table), auto_global->name)) {
+        auto_global->armed =
+            auto_global->auto_global_callback(auto_global->name);
+      } else {
+        auto_global->armed = true;
+      }
```
Comment (AlliBalliBaba) [inline frankenphp.c:141]: Good idea to only reset $_REQUEST if it's present in the symbol table.

Do we need to reset $_GLOBALS as well though? Couldn't that have other side effects?

File: frankenphp_test.go [hunk 3]
```diff
@@ -306,6 +306,61 @@ func testPostSuperGlobals(t *testing.T, opts *testOptions) {
...
+	// - Request 1 (i=1): includes file, $_REQUEST initialized with val=1
+	// - Request 3 (i=3): includes file from cache, $_REQUEST should have val=3
+	// If the bug exists, $_REQUEST would still have val=1 from request 1.
+	phpIni := make(map[string]string)
+	phpIni["opcache.jit"] = "tracing"
+	runTest(t, func(handler func(http.ResponseWriter, *http.Request), _ *httptest.Server, i int) {
+		if i%2 == 0 {
+			// Even requests: don't use $_REQUEST
+			req := httptest.NewRequest("GET", fmt.Sprintf("http://example.com/request-superglobal-conditional.php?val=%d", i), nil)
+			body, _ := testRequest(req, handler, t)
```
Comment (AlliBalliBaba) [inline frankenphp_test.go]:
```suggestion
			body, _:= testGet(fmt.Sprintf("http://example.com/request-superglobal-conditional.php?val=%d", i), handler, t)
```

File: frankenphp_test.go [hunk 4]
```diff
@@ -306,6 +306,61 @@ func testPostSuperGlobals(t *testing.T, opts *testOptions) {
...
+			assert.Contains(t, body, "SKIPPED")
+			assert.Contains(t, body, fmt.Sprintf("'val' => '%d'", i))
+		} else {
+			// Odd requests: use $_REQUEST
+			req := httptest.NewRequest("GET", fmt.Sprintf("http://example.com/request-superglobal-conditional.php?use_request=1&val=%d", i), nil)
+			body, _ := testRequest(req, handler, t)
```
Comment (AlliBalliBaba) [inline frankenphp_test.go]:
```suggestion
			body, _ := testGet(fmt.Sprintf("http://example.com/request-superglobal-conditional.php?use_request=1&val=%d", i), handler, t)
```

File: frankenphp_test.go [hunk 5]
```diff
@@ -306,6 +306,61 @@ func testPostSuperGlobals(t *testing.T, opts *testOptions) {
...
+			assert.Contains(t, body, "REQUEST:")
+			// $_REQUEST should have ONLY current request's data (2 keys: use_request and val)
+			assert.Contains(t, body, "REQUEST_COUNT:2")
+			// Verify current request data is present
+			assert.Contains(t, body, fmt.Sprintf("'val' => '%d'", i))
+			assert.Contains(t, body, "'use_request' => '1'")
+			// Critical: verify $_REQUEST has the CURRENT request's val, not stale data
+			assert.Contains(t, body, "VAL_CHECK:MATCH", "BUG: $_REQUEST contains stale data from previous request! Body: "+body)
```
Comment (AlliBalliBaba) [inline frankenphp_test.go]:
```suggestion
			assert.Contains(t, body, "REQUEST_COUNT:2", "$_REQUEST should have ONLY current request's data (2 keys: use_request and val)")
			assert.Contains(t, body, fmt.Sprintf("'val' => '%d'", i), "request data is not present")
			assert.Contains(t, body, "'use_request' => '1'")
			assert.Contains(t, body, "VAL_CHECK:MATCH", "BUG: $_REQUEST contains stale data from previous request! Body: "+body)
```

**Comment by AlliBalliBaba** [comment]
The failing test was testing super globals reset,.so likely related to this PR.

File: frankenphp.c (hunk 2 above)
Comment (AlliBalliBaba) [reply frankenphp.c:141]: Looks like re-importing `$GLOBALS` currently does [nothing](https://github.com/php/php-src/blob/5f367b8a011b6d9d2ddac08f6ff6ad0dcd39a0c2/Zend/zend.c#L911).

Still probably better to single out $_REQUEST and not re-arm since it could trigger randomly on script parsing in follow-up requests.

```suggestion
      /* JIT globals ($_REQUEST, $GLOBALS) need special handling:
       * - If in symbol_table: re-initialize with current request data
       * - If not: re-arm for potential future use during include */
      if (auto_global->name == ZSTR_KNOWN(ZEND_STR_AUTOGLOBAL_REQUEST) && zend_hash_exists(&EG(symbol_table), auto_global->name)) {
        auto_global->armed =
            auto_global->auto_global_callback(auto_global->name);
      }
```

Comment (xavierleune) [reply frankenphp.c:141]: yes good idea 👍

**Comment by xavierleune** [comment]
@AlliBalliBaba you're right, I had enabled jit in tests but it was not supported on 386 and not required

**Review by AlliBalliBaba — APPROVED** [review]

**Comment by dunglas** [comment]
Thank you very much Xavier!
