### PR TITLE
fix: watcher - handles associated events.

### LINKED ISSUE #1375: frankenphp watch directive not working on file changes
```
frankenphp {
	worker {
		file /drive1000/srv/testproject/public/index.php
		watch /drive1000/srv/testproject/public/**/*.php
	}
}
```

https://frankenphp.dev/docs/config/ is stating: 

> Workers can instead be restarted on file changes via the watch directive. This is useful for development environments.

At least for me, I need to create a new file or delete a file, only then the `filesystem change detected` is triggered. 
If I change an existing PHP file (no matter if I add or delete something), nothing will happen. Also if I copy or transfer an update for the already existing file. Spent now an hour to find out, if I did something wrong with my config or it is only triggered on filesize change (not sha). But ultimately I can say, that changes to already existing files do not trigger the filesystem change detection. 

This result could be in connection with my fstab configuration `relatime` but its nowadays quite common to use it, or `noatime`. As example btrfs should be always mounted with `noatime`.

### PR DESCRIPTION
**Pull request by AlliBalliBaba**
This changes the watcher to also check file patterns of associated events (fixes #1375).

Some editors will just create temporary files and never directly modify the original PHP file.

### CODE REVIEW

File: internal/watcher/watch_pattern_test.go [hunk 1]
```diff
@@ -145,6 +146,21 @@ func TestInValidExtendedPatterns(t *testing.T) {
...
+func TestAnAssociatedEventTriggersTheWatcher(t *testing.T) {
+	watchPattern, err := parseFilePattern("/**/*.php")
+	assert.NoError(t, err)
+	watchPattern.trigger = make(chan struct{})
+
+	go handleWatcherEvent(watchPattern, "/path/temorary_file", "/path/file.php", 0, 0)
+
+	select {
+	case <-watchPattern.trigger:
+		assert.True(t, true)
```
Comment (dunglas) [inline internal/watcher/watch_pattern_test.go:158]: This line can be removed, right?

**Review by dunglas — APPROVED** [review]

File: internal/watcher/watch_pattern_test.go (hunk 1 above)
Comment (AlliBalliBaba) [reply internal/watcher/watch_pattern_test.go:158]: True
