### PR TITLE
fix missing metrics

### LINKED ISSUE #1365: Metrics is missing on frankenphp >= 1.4.0
### What happened?

`frankenphp_*` metrics were there  before v1.4.0

I did a quick debug and found out that caddy 2.9 changed the flow of how the module should hook to use the metrics registry
https://github.com/dunglas/frankenphp/blob/be2e4714f5624ba48824af07ad5e41ffafacda1b/caddy/caddy.go#L43 current frankenphp implementation is still relying on this https://github.com/caddyserver/caddy/pull/3709 but in https://github.com/caddyserver/caddy/commit/41f5dd56e1b93ec815daa98dd1f1caa7f2087312  (caddy v2.9.0) changed the flow to get the metrics registry

### Build Type

Docker (Debian Bookworm)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
-
```

### Relevant log output

```shell
-
```

### PR DESCRIPTION
**Pull request by IndraGunawan**
closes #1365 

update Caddy metrics registry
as of Caddy v2.9 (https://github.com/caddyserver/caddy/commit/41f5dd56e1b93ec815daa98dd1f1caa7f2087312) it changed the flow to get the metrics registry

### CODE REVIEW

**Comment by withinboredom** [comment]
Nice catch, but in the future can you fill in the PR description with what your PR does? This way we don't have to go spelunking through issues and other project PRs to figure out what you are trying to accomplish. It only takes you a few minutes, but saves everyone reviewing a ton of time.

File: caddy/caddy.go [hunk 1]
```diff
@@ -58,6 +56,8 @@ type FrankenPHPApp struct {
 	NumThreads int `json:"num_threads,omitempty"`
 	// Workers configures the worker scripts to start.
 	Workers []workerConfig `json:"workers,omitempty"`
+
+	metrics *frankenphp.PrometheusMetrics
```
Comment (withinboredom) [inline caddy/caddy.go:60]: This should use the interface `Metrics` instead.

**Comment by dunglas** [comment]
The Mercure module likely needs the same refactoring btw.

**Review by dunglas — APPROVED** [review]

**Comment by withinboredom** [comment]
@dunglas this looks good to merge, but the tests have a weird failure. Is this normal?

If so, and @IndraGunawan is ready, lets merge it.

**Comment by dunglas** [comment]
All failures are known random network/rate limit issues or flaky tests. It's "normal".

**Comment by dunglas** [comment]
Thanks!!
